#!/usr/bin/env php
<?php

function includeIfExists(string $file): mixed
{
    if (!file_exists($file)) {
        return null;
    }

    return include $file;
}

$loader = includeIfExists(__DIR__ . '/vendor/autoload.php');
if (!$loader instanceof \Composer\Autoload\ClassLoader) {
    $loader = includeIfExists(__DIR__ . '/../../autoload.php');
}

if (!$loader instanceof \Composer\Autoload\ClassLoader) {
    die(
        'You must set up the project dependencies, run the following commands:' . PHP_EOL .
        'curl -sS https://getcomposer.org/installer | php' . PHP_EOL .
        'php composer.phar install' . PHP_EOL
    );
}

use KoenVanMeijeren\ConvertToJUnitXML\Command\ConvertBashGrepCommand;
use KoenVanMeijeren\ConvertToJUnitXML\Command\ConvertPhpMagicNumbersCommand;
use KoenVanMeijeren\ConvertToJUnitXML\Command\FileToConverterBridgeCommand;
use KoenVanMeijeren\ConvertToJUnitXML\Converters\Bash\Grep;
use KoenVanMeijeren\ConvertToJUnitXML\Converters\Npm\Audit;
use KoenVanMeijeren\ConvertToJUnitXML\Converters\PhpMagicNumbers\PhpMagicNumbersConverter;
use KoenVanMeijeren\ConvertToJUnitXML\Converters\Sensiolabs\SecurityCheck;
use KoenVanMeijeren\ConvertToJUnitXML\Converters\StandardJs\StandardJs;
use KoenVanMeijeren\ConvertToJUnitXML\Converters\Stylelint\Stylelint;
use Symfony\Component\Console\Application;
use KoenVanMeijeren\ConvertToJUnitXML\Command\ConvertNpmAuditCommand;
use KoenVanMeijeren\ConvertToJUnitXML\Command\ConvertSensiolabsSecurityCheckCommand;
use KoenVanMeijeren\ConvertToJUnitXML\Command\ConvertStandardJsCommand;
use KoenVanMeijeren\ConvertToJUnitXML\Command\ConvertStylelintCommand;

$application = new Application('Convert to JUnit XML');
$application->add(new ConvertBashGrepCommand(new Grep()));
$application->add(new ConvertNpmAuditCommand(new Audit()));
$application->add(new ConvertSensiolabsSecurityCheckCommand(new SecurityCheck()));
$application->add(new ConvertStandardJsCommand(new StandardJs()));
$application->add(new ConvertStylelintCommand(new Stylelint()));
$application->add(new ConvertPhpMagicNumbersCommand(new PhpMagicNumbersConverter()));
$application->add(new FileToConverterBridgeCommand());

$application->run();
