#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';

use Symfony\Component\Console\Application;
use TijsVerkoyen\ConvertToJUnitXML\Command\ConvertNpmAuditCommand;
use TijsVerkoyen\ConvertToJUnitXML\Converters\Npm\Audit;

$application = new Application('Convert to JUnit XML');
$application->add(new ConvertNpmAuditCommand(new Audit()));
$application->run();
